### ISSUE TITLE
Multiline function call

### ISSUE THREAD

**Issue by Peekmo** [nondev/raxe#18]
I really need traditional multiline function call like this : 

```ruby
def module = Angular
        .module("mod", [])
        .factory(Config.new)
        .controller("Controller", controller)
```

Because I'm using a lot of chained functions, and the current style is really bad.

**Comment by deathbeam** [comment]
Done, solved it with this commit 9d2104cb13bf7dce469fcb3d7767754228e7ef02 . It may not be perfect, but hopefully it will work.
