### ISSUE TITLE
Semicolons

### ISSUE THREAD

**Issue by deathbeam** [nondev/raxe#2]
What needs to be done:

* Do not insert for multiline statements - if line ends with
  * +
  * -
  * *
  * /
  * =
  * .
  * , - done
  * ( - done
  * [ - done
  * { - done

* Do not insert at end if in array or structure

And some more things. This is last thing missing to atleast go to pre-alpha of Raxe. Semicolons..

**Comment by Peekmo** [comment]
Multiline calls fails

```raxe
self class

def self.main()
  def arr = Array<String>.new()
  arr
    .array()
    .join("/")
end
```

transpile into

```haxe
package examples;using Lambda; class HelloWorld {

static public function main(){
  var arr =new  Array<String>();
  arr
    .array();
    .join("/");
};
}
```

**Comment by deathbeam** [comment]
This type of syntax will not be supported soon. There is no easy way to check if you are in multiline statement, if you **start** previous statement with a dot. But I plan to support this syntax

```ruby
self class

def self.main()
  def arr = Array<String>.new()
  arr.array().
    join("/")
end
```

So character specifying that it is multiline statement is last token on previous line.

**Comment by Peekmo** [comment]
So, when using autocomplete, you can't play with multilines.
A bit sad :(

**Comment by deathbeam** [comment]
Hmm now I get an idea. I can safely also get next token and check if it is "semicolon ignoring" one. So I can also support syntax like yours :D

**Comment by Peekmo** [comment]
Yep, it will fix also multiline arrays :+1:

**Comment by deathbeam** [comment]
It will not probably :D Anyway, added support for multiline expressions but with my style for now, yours (and most used one :/ ) is not working yet.

**Comment by deathbeam** [comment]
Added also support for yours syntax :D

**Comment by deathbeam** [comment]
I think I can close this now.

**Comment by Peekmo** [comment]
Wouhou ! I'll try later thank you :+1:
