### ISSUE TITLE
Allow trailing argument in a call

### ISSUE THREAD

**Issue by back2dos** [nondev/raxe#21]
Looking at [example code](https://github.com/nondev/raxe/blob/master/src/raxe/raxefile/Raxefile.rx#L28) I wish that this

```
script.variables.set("cp", do(from : String, to : String)
  File.copy(from, to)
end)
```

Could be written as this:

```
script.variables.set("cp") do(from : String, to : String)
  File.copy(from, to)
end
```

While this doesn't work for arbitrary expression (without introducing weird ambiguity such as `foo.bar(4)-5`, which could be interpreted as `foo.bar(4,-5)`), it would be cool for blocks and also object literals, [e.g.](https://github.com/nondev/raxe/blob/master/src/raxe/raxefile/Raxefile.rx#L44):

```
script.variables.set("env") {
  get: do(key : String)
    return Sys.getEnv(key)
  end,
  set: do(key : String, value : String)
    Sys.putEnv(key, value)
  end,
}
```

**Comment by deathbeam** [comment]
Yes this will be awesome, but a bit hard for Raxe compiler (but doable). But this is one of my goals, because it is awesome and nice looking feature :)

**Comment by kobi2187** [comment]
confusing in my opinion, because you don't know what to expect from "set" method in your example.
in the first version, you understand it takes a String, and a Function. 
The second one looks like two expressions unrelated to each other.

**Comment by deathbeam** [comment]
I already added this, but with this syntax:

```ruby
script.variables.set("env") => {
  get: do(key : String)
    return Sys.getEnv(key)
  end,
  set: do(key : String, value : String)
    Sys.putEnv(key, value)
  end,
}
```

So with the `=>` arrow from tink_lang.

**Comment by back2dos** [comment]
Aw, man, I was so hoping for first class support! :dancer: 

Would it be hard to insert the arrow automatically, e.g. if you encounter `){`?
