### ISSUE TITLE
Table-like structure

### ISSUE THREAD

**Issue by deathbeam** [nondev/raxe#25]
So, I was thinking about emulating table-like declaration for structures, maps and arrays. So for all of them, you will use `{}`. Example:

```ruby
def array = { 1, 2, 3 }
# Compiled to: var array = [ 1, 2, 3 ]

def map = { "a" => 1, "b" => 2, "c" => 3 }
# Compiled to: var map = [ "a" => 1, "b" => 2, "c" => 3 ]

def structure = { a:  1, b:  2, c: 3 }
# Compiled to: var structure = { a:  1, b:  2, c: 3 }
```

What do you think?

**Comment by cleverlycoding** [comment]
For me, everything is ok, except for the arrays, `[]` syntax is stuck in my head and it would be confusing for me.

**Comment by deathbeam** [comment]
Yes I know it can be confusing first, but once you will get used to it it can really simplify things.

**Comment by cleverlycoding** [comment]
I agree, and it's not like if it was a big change or something like that. Even some C based languages use that notation

**Comment by deathbeam** [comment]
Added this notation, example here: https://github.com/nondev/raxe/blob/master/examples/Tables.rx
