### ISSUE TITLE
annotations and semicolon

### ISSUE THREAD

**Issue by francescoagati** [nondev/raxe#4]
Annotations are transpiled with semicolons

```
self class

@:pippa(123)
def self.main()
  trace("Hello World")
end
```

```
package ;using Lambda; class HelloWorld {

@:pippa(123);
static public function main(){
  trace("Hello World");
};
}

```

**Comment by deathbeam** [comment]
I think that it is because you have curlys in annotation and transpiler is thinking that it is method call. Thank you for report, I will look at it.

**Comment by francescoagati** [comment]
works now thanks :-)
